apiVersion: v1
kind: Service
metadata:
  labels:
    app: jadzia-flask-app
  name: jadzia-flask-service
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort 
  selector:
    app: jadzia-flask-app
status:
  loadBalancer: {}

